version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql-despesas-project
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - despesas-project-data:/var/lib/mysql

volumes:
  despesas-project-data: