spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gerenciador_despesas
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
